### ISSUE TITLE
Safe for Basic Auth?

### ISSUE THREAD

**Issue by creese** [not-kennethreitz/flask-sslify#13]
I'm using basic auth. If the client requests with HTTP, are credentials sent in plain text before the redirect occurs?

**Comment by ryan-lane** [comment]
Yes, credentials are sent before the redirect. There's no getting around that. #27 seems like a good way to encourage clients to use HTTPS, rather than HTTP, by sending an abort with a 403. Obviously that isn't sslifying the app, but is instead saying "you must use HTTPS".
