### ISSUE TITLE
Support Blueprints explicitly.

### ISSUE THREAD

**Issue by mbr** [not-kennethreitz/flask-sslify#20]
This is more of a documentation and commitment thing - it's almost possible to use the extension on a Blueprint as-is, by simply doing `SSLify(my_blueprint)` and working around the app.debug issue.

That seems to be a good usecase for the future (for example it may be convenient to only protect an admin area blueprint instead of the whole site).

There's not official API for extending blueprints that I know of. Maybe adding an init_blueprint() method would be a way to go?

**Comment by mbr** [comment]
See #22 for the minimal fix to support this.

**Comment by quietlyconfident** [comment]
Should this issue be closed if the patch was merged?

**Comment by sfriesel** [comment]
#28 broke the implicit support again afaict

**Comment by kennethreitz** [comment]
@sfriesel
