### ISSUE TITLE
Update PyPi with latest code.

### ISSUE THREAD

**Issue by Robpol86** [not-kennethreitz/flask-sslify#24]
When you get a chance can you update your tarball on PyPi to the same code you have on GitHub? It's a little bit behind (2012-11-16).

https://pypi.python.org/pypi/Flask-SSLify

**Comment by fgimian** [comment]
+1 please :smile: 

Thanks heaps!
Fotis

**Comment by quietlyconfident** [comment]
+1 please

**Comment by joshfriend** [comment]
:+1:

**Comment by sfriesel** [comment]
this is fixed

**Comment by joshfriend** [comment]
There is a 1.5 version on PyPI, but no corresponding Git tag on the repo yet.
