### ISSUE TITLE
Exceptions for permissible HTTP situations

### ISSUE THREAD

**Issue by quietlyconfident** [not-kennethreitz/flask-sslify#25]
Currently, SSLify watches DEBUG to see if it should SSLify or not a request.  However, it would be useful to be able to provide a more advanced criteria for per-request SSLification.

For example, using SSLify on Amazon Elastic Beanstalk, SSLify keeps trying to redirect the health checker, which results in failing checks.  It would be nice to be able to add a "criteria" to the list of criteria in redirect_to_ssl, so that you could check to see if, for example, the user agent was the ELB Health Checker and the requested URL was the URL to be tested.  Or even, just to exclude a URL from the SSLification.

If the maintainer would be open to such a patch, I'll submit it.

**Comment by bruce-lyft** [comment]
+1
Just ran into this same issue, with AWS ELB's.
CF:

https://github.com/kennethreitz/flask-sslify/pull/26

**Comment by ryan-lane** [comment]
+1 Also would like to be able to exclude healthcheck urls.

**Comment by tofias** [comment]
I'm having a hell of a time trying to use nginx as a reverse proxy for a portion of an app and I'd love to be able to exclude a blueprint (or a list of blueprints) from redirection.

**Comment by quietlyconfident** [comment]
Sorry to be a party pooper; I'm no longer using flask ATM, so I'm not going to be writing the patch :)  But I still think it would be a good idea if someone else would do it.

**Comment by ryan-lane** [comment]
Assuming a PR will be merged to make this possible, I'd be happy to write the patch. I just need to know it's going to get merged. I can make it a bit more generic than #26, as well.

**Comment by tofias** [comment]
I wrote one over the weekend. I guess I should share.

**Comment by tofias** [comment]
Okay. I made my first pull request on Github. Who buys the beer? https://github.com/kennethreitz/flask-sslify/pull/28

**Comment by ryan-lane** [comment]
If it gets merged I'll buy you one, whenever you're in SF. ;)

**Comment by ryan-lane** [comment]
Resolved via #28
