### ISSUE TITLE
Don't send HSTS headers over non-HTTPS connections

### ISSUE THREAD

**Issue by nvie** [not-kennethreitz/flask-sslify#5]
From the Wikipedia page on HSTS:

> _"Strict-Transport-Security headers must be sent via HTTPS responses only. Client implementations must not respect STS headers sent over non-HTTPS responses, or over HTTPS responses which are not using properly configured, trusted certificates. The following server configuration snippets should be within the context of an SSL site configuration block, and the code examples are intended to be within the context of HTTPS responses only."_

So https://github.com/kennethreitz/flask-sslify/blob/6735984ce259aee0d042c9e36d5d79040ccd0319/flask_sslify.py#L54 should be returning HSTS-headers only for HTTPS responses.

I'm not sure what's the best criterium to decide whether the current response is secure in Flask, though. Ideas?

**Comment by kennethreitz** [comment]
Seems reasonable to me. Clients don't honor it though, so it's not a big deal. I don't mind adding the check.
